# >>>>>>>>>>>>>  Booleans Variables   <<<<<<<<<<<<<<<<<<<<

print('\n>>>>>>>>>>>>>>>>>>>>>>>>>> Boolean Values <<<<<<<<<<<<<<<<<<<<<<<<<\n')

print(10 > 900)
print(10 == 9)
print(10 < 9)

print('\n>>>>>>>>>>>>>>>>>>>>>>>>>>  If statement <<<<<<<<<<<<<<<<<<<<<<<<<\n')                        

a = 200
b = 33

if b > a:
    print("b is greater than a")
else:
    print("b is not greater than a")



print('\n>>>>>>>>>>>>>>>>>>>>>>>>>> Evaluate Values and Variables  <<<<<<<<<<<<<<<<<<<<<<<<<\n')  

print(bool("Hello"))
print(bool(15))